version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Riga
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      rust-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
